# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-licence:
   runs-on: ubuntu-latest
   steps:
     - name: Check lic
       run: echo "ok"
  build:
    strategy:
      fail-fast: false
      matrix:
        platform-version: [ 201, 202 ]
    timeout-minutes: 60
    env:
      ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform-version }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        if [ "${ORG_GRADLE_PROJECT_platformVersion}" == "201" ]; then
          echo "platform 201"
          exit 1
        else
          echo "platform 202"
        fi

  # This job is successful if all depend jobs are successful. To be able to merge the PR, this job must be successful
  #
  all-checks:
    needs: [build, check-licence]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    env:
      JOB_CONTEXT: ${{ toJson(needs) }}
    steps:
    - name: Finish check
      run: echo "--->$JOB_CONTEXT"
